included:
  - "Foundation Lab"
  - Physiqa
  - Psylean
  - "Adapter Studio"

excluded:
  - Carthage
  - Pods
  - DerivedData
  - build

line_length:
  warning: 140
  error: 140
  ignores_comments: true
  ignores_urls: true

type_body_length:
  warning: 200
  error: 300

file_length:
  warning: 600
  error: 800

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 40
    error: 50

type_name:
  max_length:
    warning: 50
    error: 60

function_body_length:
  warning: 60
  error: 100

nesting:
  type_level:
    warning: 3
    error: 5