//
//  ModelCompareResult.swift
//  Adapter Studio
//
//  Created by Rudrank Riyam on 10/22/25.
//

import Foundation

/// Combined results emitted when the comparison run finishes.
struct ModelCompareResult: Sendable {

    /// Prompt submitted to both models.
    let prompt: String

    /// Summary generated by the baseline system model.
    let base: ModelCompareResponseSummary?

    /// Summary generated by the adapter model, if available.
    let adapter: ModelCompareResponseSummary?
}
