//
//  ModelCompareResponseSummary.swift
//  Adapter Studio
//
//  Created by Rudrank Riyam on 10/22/25.
//

import Foundation
import FoundationModels

/// Final snapshot of the text generated by a single model.
struct ModelCompareResponseSummary: Sendable {

    /// Model that produced the response.
    let source: ModelCompareSource

    /// Fully aggregated response text.
    let text: String

    /// Timing metrics captured for the run.
    let metrics: ModelCompareResponseMetrics

    /// Transcript entries associated with the response.
    let transcript: [Transcript.Entry]
}
